name: instagramclone
description: Clone de Instagram focado em compra e venda de imóveis.

environment:
  sdk: ">=3.3.0 <4.0.0"      # intervalo seguro p/ Dart 3
  flutter: ">=3.22.0"        # (opcional) garante Flutter 3.22+

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Navegação
  go_router: ^14.0.1

  # Firebase
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.4.7
  firebase_auth: ^5.0.0

  # Imagem
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1

  # Vídeo
  video_player: ^2.5.1

  # Estado
  flutter_riverpod: ^2.5.1

  # Ícones extras (opcional, mas útil)
  iconsax: ^0.0.8

  # Utilidades
  intl: ^0.19.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: any

flutter:
  uses-material-design: true        # ← AGORA no local correto
