// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNyQ5nUgqlMnxUTDxe_1hA_71CC4Zn1N0',
    appId: '1:320579321498:web:3d04d006f403da94446923',
    messagingSenderId: '320579321498',
    projectId: 'instaclone-a55ab',
    authDomain: 'instaclone-a55ab.firebaseapp.com',
    storageBucket: 'instaclone-a55ab.firebasestorage.app',
    measurementId: 'G-VEE2Y1PGQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0IKvDJ8ofoZR0jJGDGjkCO58ayasehKo',
    appId: '1:320579321498:android:a8f3f25253f390e7446923',
    messagingSenderId: '320579321498',
    projectId: 'instaclone-a55ab',
    storageBucket: 'instaclone-a55ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARDITWjZUx6dmAgYWYKmV81AVD1ZwGQFw',
    appId: '1:320579321498:ios:ff16c4388cc610d1446923',
    messagingSenderId: '320579321498',
    projectId: 'instaclone-a55ab',
    storageBucket: 'instaclone-a55ab.firebasestorage.app',
    iosClientId: '320579321498-ektvs4b6dqj31ou9e0u0g9vhuhs2rucc.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARDITWjZUx6dmAgYWYKmV81AVD1ZwGQFw',
    appId: '1:320579321498:ios:ff16c4388cc610d1446923',
    messagingSenderId: '320579321498',
    projectId: 'instaclone-a55ab',
    storageBucket: 'instaclone-a55ab.firebasestorage.app',
    iosClientId: '320579321498-ektvs4b6dqj31ou9e0u0g9vhuhs2rucc.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNyQ5nUgqlMnxUTDxe_1hA_71CC4Zn1N0',
    appId: '1:320579321498:web:e5264fbe3454b50d446923',
    messagingSenderId: '320579321498',
    projectId: 'instaclone-a55ab',
    authDomain: 'instaclone-a55ab.firebaseapp.com',
    storageBucket: 'instaclone-a55ab.firebasestorage.app',
    measurementId: 'G-KZ9J142L9E',
  );
}
